services:
  clashperk_bot:
    image: 432159388664.dkr.ecr.us-east-1.amazonaws.com/clashperk-bot:latest
    restart: always
    container_name: clashperk_bot
    # build:
    #   context: .
    env_file:
      - .env
    mem_limit: 10gb
    ports:
      - '8070:8070'
    healthcheck:
      test: wget -qO - localhost:8070 || exit 1
      interval: 15s
      timeout: 10s
      retries: 120
    networks:
      - default_net

  # Start with: docker compose --profile dev up -d
  clickhouse:
    profiles: ['dev']
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    restart: always
    ports:
      - 8123:8123
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    mem_limit: 1g
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1

  redis:
    profiles: ['dev']
    container_name: redis
    image: redis:latest
    restart: always
    mem_limit: 1g
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: --requirepass password


  mongodb:
    profiles: ['dev']
    container_name: mongodb
    image: mongo:8
    restart: always
    mem_limit: 1g
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - 'mongodb_data:/data/db'
      - 'mongodb_config:/data/configdb'
      - './scripts/start_mongo.sh:/start_mongo.sh'
    entrypoint: ['/bin/bash', '/start_mongo.sh']
    command: --bind_ip_all --replSet rs0 --keyFile /data/configdb/keyFile.pem

volumes:
  redis_data:
    external: false
  clickhouse_data:
    external: false
  clickhouse_logs:
    external: false
  mongodb_data:
    external: false
  mongodb_config:
    external: false

networks:
  default_net:
    external: true
    name: default_net
