name: eslint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: eslint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Init Submodule
        run: git submodule init && git submodule update --remote

      - name: NPM Install
        run: npm i

      - name: Run ESLint
        run: npm run test

      - name: Build
        run: npm run build

      - name: Check Duplicates
        run: npm run check:locales
