name: CI/CD

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Init Submodule
        run: git submodule init && git submodule update --remote

      - name: NPM Install
        run: npm i

      - name: Run ESLint
        run: npm run test

      - name: Build
        run: npm run build
